# SPDX-FileCopyrightText: Copyright (c) 2025 Zerocracy
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: make
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  make:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: make
